<<<<<<< HEAD
env:
  global:
  - ARTIFACTS_AWS_REGION=us-east-1
  - ARTIFACTS_S3_BUCKET=qubell-starter-kit-artifacts
  - QUBELL_TENANT=https://express.qubell.com
  - PROVIDER_TYPE=aws-ec2
  - PROVIDER_REGION=us-east-1
  - secure: dYzrzeAQwYwmTcbTTHMFXm9Ht3T2nNSsHh73/X9WbgmYzMavhp0WC+KmVxf4NIuTRwfYlOrlLBSbG4tGn1VRGaQydVHdfZ7zZzxON2H3puGZN3ChXAEw910P98olSlQ34udhvDGSqfb+VWvj2TRdD3WHkjM74wxqu2ZI30E8ZJ8=
  - secure: QhX0bqhZIviQ+P0qq/ZxhOHl/UIJJ+Tc4adiIMftvFHJgQsdosrgSQosfPiUMJyUqxWVMLSXubmXtUWJhpfQdNhvtERTxwq2ekstAVXNtU8UJwyVE8vq1XUJtX09dOD0UOTAOKiBC4R3AqJNZ6rO+0JDC16ZfD8B3a4e0bgT8wM=
  - secure: h2JciDrj4eFr7pM31c7IktLcLKceZi4sbE8IB9EsfqsTsMlalQFywjeDV/S6ISURV5hg+MW3vp0m8CcadGNzOYDOmlAKiMwtpCBXGUaQdjCAhPrRFyG9q2hs6FkSMgOhxMsVkfOjqEzm0FBn77vh6wYh0wuUhyQBb51Vpn46eNM=
  - secure: HmYh43XUa1aHI6i4zbfdNRO99h8VX+E4hxImiMUB6fmkgStRZARuczhxAzB3ntzsR5pbG+U4+KZccYmP8h5MmGI49nlLl9YXdyG6ddWC1GmUAnfPFhjyauamLSULsnPBthWbVKW8AwyF4U3ajFcVxRQYIaRTsO5fVmfQt9J2y5U=
  - secure: QafTu+pWtynCGP25XhReghmDTM5zi6IV5/Fm9ur4Ln1rQwibbFURUd2YmGoktdw3Fc1mCqmazq1uPqgmy55ULokXJ9wPHYR2Tl1aZYG93Xgb4Sg11/lc+KtuPI39M/nN3amQ8y1dRJRXQNXQm5HivcnSsP6jHjI43q/A22PKo6Y=
  - secure: X0ndAbYgRLQi5xRmc74hdB/TvpKdnWoSHXm5+np7CdUtHFe+8MK8Fe9RbzIqoYh6jL4ZLgCo/jCbzmgQk33Un4hprP94Z4suLweXhHLTLHCVyWQcHY6dK84mlZeIGuYWV0BZwSOd0WnrKtBWo+siVia+7Ju1teJ07f7jwH7tMoY=
  - secure: F/1Obir+rpY36f+HVxLe0e9QWJv5GYhJ0s4mmsOo/yheM+D5i/d1RuVhznMzKp2mInpQTlsjHlb+MQWQBkXncsJNiqA7a+b2DwyxM47pKBSwaTyVXoBVaqZFrCVm4+BfLMRnsx0F6auqN5NXlo6RDwWo2lCVNlWbhzzNlYwFwyo=
language: python
python:
- '2.7'
install: pip install -r test/requirements.txt
before_script:
- gem install --version 0.8.9 faraday --no-ri --no-rdoc
- gem install travis-artifacts --no-ri --no-rdoc
- git submodule update --init --recursive
script: ./build.sh
=======
language: ruby
gemfile:
- gemfiles/travis.gemfile
rvm:
- 1.9.3
env:
  global:
  - secure: QEMzc3ZnN95rGHm9xWz5rox41gSqSiorICknyYK4ZrzPI4WQIZeuP/3QXg+HsFGlc7CtQ5KpqL5P2CQDl+0GxkylE9imRvJ8qadSLCZo0nPLRMs+1qhnFeKJT2k0z6CavWRCugH5JY+0jFkIjYFwds7qvLWMwiOSknrie2OA0DQ=
  - secure: IW0OnmKdOVZvI0eGWo7/AxhDCAcSQVJRSCYHDQ4BkCCrbJIdD+RsI6iNQaYn911ObXaOApWL3FYrG1gsjuHTtWz8C3e++22369FufgOQJMATJtLukTsPT3K6QnWTsruso859/sP9SowwAjzFshNtXGyYDVMhFEUjL/bSsX1Owh4=
  - secure: i7Tj/CXnmiptAcy2Jue+Whme6vJ+kQDLHlHO22vq4t/88alFF9yfTgVc7W9vG5YjtuX6PVIYvIlul7FJwwBm8LgkFKGJET74Ox+e1YbyHhdtxbU/H6CITVYUnh5i1jOCze508Lh3auN5MIJuFt72XYEC/RRxod+QrvgL1bvcJCM=
  matrix:
  - KITCHEN_INSTANCE='default-ubuntu-1204'
  - KITCHEN_INSTANCE='default-ubuntu-1004'
  - KITCHEN_INSTANCE='default-centos-64'
  - KITCHEN_INSTANCE='default-centos-53'
script:
- bundle exec foodcritic ./ -f 'any'
- bundle exec kitchen test $KITCHEN_INSTANCE
after_script:
- bundle exec kitchen destroy $KITCHEN_INSTANCE
notifications:
  email:
  - abutovich@qubell.com
>>>>>>> build/master
