env:
  global:
  - ARTIFACTS_AWS_REGION=us-east-1
  - ARTIFACTS_S3_BUCKET=qubell-starter-kit-artifacts
  - QUBELL_TENANT=https://express.qubell.com
  - PROVIDER_TYPE=aws-ec2
  - PROVIDER_REGION=us-east-1
  - secure: dYzrzeAQwYwmTcbTTHMFXm9Ht3T2nNSsHh73/X9WbgmYzMavhp0WC+KmVxf4NIuTRwfYlOrlLBSbG4tGn1VRGaQydVHdfZ7zZzxON2H3puGZN3ChXAEw910P98olSlQ34udhvDGSqfb+VWvj2TRdD3WHkjM74wxqu2ZI30E8ZJ8=
  - secure: TbwN6/wHyF7wxMEHBv7SUktZDv9MHtVNeeteI6JSHFZn3KpmgU4u4uNWzjTjdzmzxG+gtK9e+rKt6lhKiwd4Yz4EX6CFCqyHMx5iD1X4ywhJ9RcEIq7mrsNy0D+zWiw0UlPG0N4uSX55EK/F/mkBV5Q4UPD1BsusKeqIbxCffbw=
  - secure: V3gCzkLgvcWPTnbpSFlvLwSMxVKmd03INHy1MXxthmyFWTAy+dr1UWVnT+LcbczRZ8JTzURxJzXuj2WnEiZ0exjYdyYmoCyPjG9UH7aaTKNl4eXjQPIOPpuA8oHrdRD8uhzJWuZF/Q4h6mf1/ZvvrTFLX4g4d8UyuHFtSfFErKE=
  - secure: AG2BP8Vd0KgDgO4KUr3PBpzXWnXZCMTgtcbF89xodh0nUyvL/v0YuDMosckX9jhw2iDsNaVyaFakQjk/i+9+Ygd6OAjcmjQktGDbi56qg01h2xSQS/DYc/Q8Ah+IiJYUEO/vFSSRKkHAN/Z7/XrWMJjDxVgqW5E5TgJhLV2K3O0=
  - secure: dECNqb0IbQ/SsA3Qg9eo/fMypY64FaMk4+dk2t0OOvfI/Eg9HHO6Xc/MknCoA7VRm80PA6jbHirdvt/XSkMS7jVDa6O6KXNSsoFgxyxM1wNtZ7UVF4hf0sLxP9LAXn8RTy1jXZg8cJ9Suby88k7HRftUxHznOSZhcEDWNVhTBv8=
  - secure: QhX0bqhZIviQ+P0qq/ZxhOHl/UIJJ+Tc4adiIMftvFHJgQsdosrgSQosfPiUMJyUqxWVMLSXubmXtUWJhpfQdNhvtERTxwq2ekstAVXNtU8UJwyVE8vq1XUJtX09dOD0UOTAOKiBC4R3AqJNZ6rO+0JDC16ZfD8B3a4e0bgT8wM=
  - secure: h2JciDrj4eFr7pM31c7IktLcLKceZi4sbE8IB9EsfqsTsMlalQFywjeDV/S6ISURV5hg+MW3vp0m8CcadGNzOYDOmlAKiMwtpCBXGUaQdjCAhPrRFyG9q2hs6FkSMgOhxMsVkfOjqEzm0FBn77vh6wYh0wuUhyQBb51Vpn46eNM=
language: python
python:
- '2.7'
install: pip install -r test/requirements.txt
before_script:
- gem install travis-artifacts --no-ri --no-rdoc
- git submodule update --init --recursive
script: ./build.sh
